apiVersion: apps/v1
kind: Deployment
metadata:
  name: obs
  namespace: monitoring
  labels:
    app.kubernetes.io/name: obs
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: obs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: obs
    spec:
      containers:
        - name: obs
          image: obs:dev
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 2112
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: metrics
            initialDelaySeconds: 1
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 500m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
            runAsGroup: 65532
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
